In [ ]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\mehal\Desktop\Yamina\vsc\conso-elec-gaz-annuelle-par-secteur-dactivite-agregee-commune.csv',
    encoding="utf-8",
    sep=';'
)

C:\Users\mehal\AppData\Local\Temp\ipykernel_1724\1540522251.py:3: DtypeWarning: Columns (25,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [2]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
df

,Opérateur,Année,Filière,Consommation Agriculture (MWh),Nombre de points Agriculture,Nombre de mailles secretisées (agriculture),Indique qualité Agriculture,Consommation Industrie (MWh),Nombre de points Industrie,Nombre de mailles secretisées (industrie),...,Libellé Commune,Code EPCI,Libellé EPCI,Code Département,Libellé Département,Code Région,Libellé Région,id_filiere,Consommation totale (MWh),Code_postal
0,GRDF,2021,Gaz,0.00,0,1,0.000,4662.25037,10,0,...,Appoigny,200067114,CA de l'Auxerrois,89,Yonne,27,Bourgogne-Franche-Comté,200,19903.81639,89380
1,GRDF,2021,Gaz,0.00,0,0,0.000,466.96205,4,0,...,Augy,200067114,CA de l'Auxerrois,89,Yonne,27,Bourgogne-Franche-Comté,200,5936.61816,89290
2,GRDF,2021,Gaz,0.00,0,1,0.000,33572.36146,14,1,...,Avallon,200039758,"CC Avallon, Vézelay, Morvan",89,Yonne,27,Bourgogne-Franche-Comté,200,79188.02222,89200
3,GRDF,2021,Gaz,0.00,0,0,0.000,84.09507,1,0,...,Bassou,248900383,CC de l'Agglomération Migennoise,89,Yonne,27,Bourgogne-Franche-Comté,200,2601.05236,89400
4,GRDF,2021,Gaz,0.00,0,0,0.000,0.00000,0,1,...,Bazarnes,200067080,CC Chablis Villages et Terroirs,89,Yonne,27,Bourgogne-Franche-Comté,200,1195.97512,89460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501560,Enedis,2012,Electricité,0.00,0,0,0.000,135.46000,1,0,...,Saint-Ulphace,247200686,CC du Pays de l'Huisne Sarthoise,72,Sarthe,52,Pays de la Loire,100,1284.06000,72320
501561,Enedis,2012,Electricité,0.00,0,0,0.000,387.38000,1,0,...,Saint-Vincent-du-Lorouër,200070373,CC Loir-Lucé-Bercé,72,Sarthe,52,Pays de la Loire,100,4203.72000,72150
501562,Enedis,2012,Electricité,238.20,6,0,0.989,29.49000,1,0,...,Savigné-sous-le-Lude,200073112,CC Sud Sarthe,72,Sarthe,52,Pays de la Loire,100,2093.96000,72800
501563,Enedis,2012,Electricité,0.00,0,0,0.000,19659.51000,7,0,...,Solesmes,247200090,CC de Sablé-sur-Sarthe,72,Sarthe,52,Pays de la Loire,100,33036.56000,72300
501564,Enedis,2012,Electricité,36.03,1,0,1.000,0.00000,0,0,...,Souillé,200068963,CC Maine Cœur de Sarthe,72,Sarthe,52,Pays de la Loire,100,2479.62000,72380

In [4]:
df.dtypes

Opérateur                                           object
Année                                                int64
Filière                                             object
Consommation Agriculture (MWh)                     float64
Nombre de points Agriculture                         int64
Nombre de mailles secretisées (agriculture)          int64
Indique qualité Agriculture                        float64
Consommation Industrie (MWh)                       float64
Nombre de points Industrie                           int64
Nombre de mailles secretisées (industrie)            int64
Indice qualité Industrie                           float64
Consommation Tertiaire  (MWh)                      float64
Nombre de points Tertiaire                           int64
Nombre de mailles secretisées (tertiaire)            int64
Indice qualité Tertiaire                           float64
Consommation Résidentiel  (MWh)                    float64
Nombre de points Résidentiel                         int64
Nombre de mailles secretisées (résidentiel)          int64
Indice qualité Résidentiel                         float64
Thermosensibilité (MWh/degré-jour)                 float64
Part Thermosensible                                float64
Consommation Secteur Inconnu (MWh)                 float64
Nombre de points Secteur Inconnu                     int64
Nombre de mailles secretisées (secteur inconnu)      int64
Indice qualité Non Affecté                         float64
Code Commune                                        object
Libellé Commune                                     object
Code EPCI                                           object
Libellé EPCI                                        object
Code Département                                    object
Libellé Département                                 object
Code Région                                          int64
Libellé Région                                      object
id_filiere                                           int64
Consommation totale (MWh)                          float64
Code_postal                                         object
dtype: object

In [5]:
print("Total lignes :", len(df))
print(df.count())

Total lignes : 501565
Opérateur                                          501565
Année                                              501565
Filière                                            501565
Consommation Agriculture (MWh)                     501565
Nombre de points Agriculture                       501565
Nombre de mailles secretisées (agriculture)        501565
Indique qualité Agriculture                        501565
Consommation Industrie (MWh)                       501565
Nombre de points Industrie                         501565
Nombre de mailles secretisées (industrie)          501565
Indice qualité Industrie                           501565
Consommation Tertiaire  (MWh)                      501565
Nombre de points Tertiaire                         501565
Nombre de mailles secretisées (tertiaire)          501565
Indice qualité Tertiaire                           501565
Consommation Résidentiel  (MWh)                    501565
Nombre de points Résidentiel                       501565
Nombre de mailles secretisées (résidentiel)        501565
Indice qualité Résidentiel                         501565
Thermosensibilité (MWh/degré-jour)                 501565
Part Thermosensible                                501565
Consommation Secteur Inconnu (MWh)                 501565
Nombre de points Secteur Inconnu                   501565
Nombre de mailles secretisées (secteur inconnu)    501565
Indice qualité Non Affecté                         501565
Code Commune                                       501565
Libellé Commune                                    501547
Code EPCI                                          501547
Libellé EPCI                                       501547
Code Département                                   501565
Libellé Département                                501565
Code Région                                        501565
Libellé Région                                     501565
id_filiere                                         501565
Consommation totale (MWh)                          501565
Code_postal                                        501426
dtype: int64

In [6]:
df.isnull().sum()

Opérateur                                            0
Année                                                0
Filière                                              0
Consommation Agriculture (MWh)                       0
Nombre de points Agriculture                         0
Nombre de mailles secretisées (agriculture)          0
Indique qualité Agriculture                          0
Consommation Industrie (MWh)                         0
Nombre de points Industrie                           0
Nombre de mailles secretisées (industrie)            0
Indice qualité Industrie                             0
Consommation Tertiaire  (MWh)                        0
Nombre de points Tertiaire                           0
Nombre de mailles secretisées (tertiaire)            0
Indice qualité Tertiaire                             0
Consommation Résidentiel  (MWh)                      0
Nombre de points Résidentiel                         0
Nombre de mailles secretisées (résidentiel)          0
Indice qualité Résidentiel                           0
Thermosensibilité (MWh/degré-jour)                   0
Part Thermosensible                                  0
Consommation Secteur Inconnu (MWh)                   0
Nombre de points Secteur Inconnu                     0
Nombre de mailles secretisées (secteur inconnu)      0
Indice qualité Non Affecté                           0
Code Commune                                         0
Libellé Commune                                     18
Code EPCI                                           18
Libellé EPCI                                        18
Code Département                                     0
Libellé Département                                  0
Code Région                                          0
Libellé Région                                       0
id_filiere                                           0
Consommation totale (MWh)                            0
Code_postal                                        139
dtype: int64

In [13]:
import pandas as pd

fichier_csv = r'C:\Users\mehal\Desktop\Yamina\vsc\conso-elec-gaz-annuelle-par-secteur-dactivite-agregee-commune.csv'

# Utilise le bon séparateur
df = pd.read_csv(fichier_csv, sep=';')

# Afficher les colonnes
print("Colonnes :", df.columns.tolist())

# Nettoyer les noms de colonnes
df.columns = df.columns.str.strip()

# Vérifier si la colonne 'Année' existe
if 'Année' in df.columns:
    df_2021 = df[df['Année'] == 2021]
    print(f"Nombre de lignes pour 2021 : {len(df_2021)}")
else:
    print("⚠️ La colonne 'Année' est introuvable.")

C:\Users\mehal\AppData\Local\Temp\ipykernel_2512\1535378704.py:6: DtypeWarning: Columns (25,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(fichier_csv, sep=';')

Colonnes : ['Opérateur', 'Année', 'Filière', 'Consommation Agriculture (MWh)', 'Nombre de points Agriculture', 'Nombre de mailles secretisées (agriculture)', 'Indique qualité Agriculture', 'Consommation Industrie (MWh)', 'Nombre de points Industrie', 'Nombre de mailles secretisées (industrie)', 'Indice qualité Industrie', 'Consommation Tertiaire  (MWh)', 'Nombre de points Tertiaire', 'Nombre de mailles secretisées (tertiaire)', 'Indice qualité Tertiaire', 'Consommation Résidentiel  (MWh)', 'Nombre de points Résidentiel', 'Nombre de mailles secretisées (résidentiel)', 'Indice qualité Résidentiel', 'Thermosensibilité (MWh/degré-jour)', 'Part Thermosensible', 'Consommation Secteur Inconnu (MWh)', 'Nombre de points Secteur Inconnu', 'Nombre de mailles secretisées (secteur inconnu)', 'Indice qualité Non Affecté', 'Code Commune', 'Libellé Commune', 'Code EPCI', 'Libellé EPCI', 'Code Département', 'Libellé Département', 'Code Région', 'Libellé Région', 'id_filiere', 'Consommation totale (MWh)', 'Code_postal']
Nombre de lignes pour 2021 : 46584

In [7]:
(df == 0).sum()

Opérateur                                               0
Année                                                   0
Filière                                                 0
Consommation Agriculture (MWh)                     333159
Nombre de points Agriculture                       333088
Nombre de mailles secretisées (agriculture)        436544
Indique qualité Agriculture                        337145
Consommation Industrie (MWh)                       264154
Nombre de points Industrie                         264138
Nombre de mailles secretisées (industrie)          430734
Indice qualité Industrie                           273267
Consommation Tertiaire  (MWh)                      161926
Nombre de points Tertiaire                         162113
Nombre de mailles secretisées (tertiaire)          464951
Indice qualité Tertiaire                           173684
Consommation Résidentiel  (MWh)                     24245
Nombre de points Résidentiel                        24249
Nombre de mailles secretisées (résidentiel)        484489
Indice qualité Résidentiel                          75007
Thermosensibilité (MWh/degré-jour)                 451460
Part Thermosensible                                451460
Consommation Secteur Inconnu (MWh)                 428466
Nombre de points Secteur Inconnu                   429833
Nombre de mailles secretisées (secteur inconnu)    425408
Indice qualité Non Affecté                         435572
Code Commune                                            0
Libellé Commune                                         0
Code EPCI                                               0
Libellé EPCI                                            0
Code Département                                        0
Libellé Département                                     0
Code Région                                             0
Libellé Région                                          0
id_filiere                                              0
Consommation totale (MWh)                            2769
Code_postal                                             0
dtype: int64

In [8]:


print("🔍 Valeurs manquantes par colonne :")
print(df.isnull().sum())

print("\n🧮 Valeurs égales à 0 par colonne :")
print((df == 0).sum())

🔍 Valeurs manquantes par colonne :
Opérateur                                            0
Année                                                0
Filière                                              0
Consommation Agriculture (MWh)                       0
Nombre de points Agriculture                         0
Nombre de mailles secretisées (agriculture)          0
Indique qualité Agriculture                          0
Consommation Industrie (MWh)                         0
Nombre de points Industrie                           0
Nombre de mailles secretisées (industrie)            0
Indice qualité Industrie                             0
Consommation Tertiaire  (MWh)                        0
Nombre de points Tertiaire                           0
Nombre de mailles secretisées (tertiaire)            0
Indice qualité Tertiaire                             0
Consommation Résidentiel  (MWh)                      0
Nombre de points Résidentiel                         0
Nombre de mailles secretisées (résidentiel)          0
Indice qualité Résidentiel                           0
Thermosensibilité (MWh/degré-jour)                   0
Part Thermosensible                                  0
Consommation Secteur Inconnu (MWh)                   0
Nombre de points Secteur Inconnu                     0
Nombre de mailles secretisées (secteur inconnu)      0
Indice qualité Non Affecté                           0
Code Commune                                         0
Libellé Commune                                     18
Code EPCI                                           18
Libellé EPCI                                        18
Code Département                                     0
Libellé Département                                  0
Code Région                                          0
Libellé Région                                       0
id_filiere                                           0
Consommation totale (MWh)                            0
Code_postal                                        139
dtype: int64

🧮 Valeurs égales à 0 par colonne :
Opérateur                                               0
Année                                                   0
Filière                                                 0
Consommation Agriculture (MWh)                     333159
Nombre de points Agriculture                       333088
Nombre de mailles secretisées (agriculture)        436544
Indique qualité Agriculture                        337145
Consommation Industrie (MWh)                       264154
Nombre de points Industrie                         264138
Nombre de mailles secretisées (industrie)          430734
Indice qualité Industrie                           273267
Consommation Tertiaire  (MWh)                      161926
Nombre de points Tertiaire                         162113
Nombre de mailles secretisées (tertiaire)          464951
Indice qualité Tertiaire                           173684
Consommation Résidentiel  (MWh)                     24245
Nombre de points Résidentiel                        24249
Nombre de mailles secretisées (résidentiel)        484489
Indice qualité Résidentiel                          75007
Thermosensibilité (MWh/degré-jour)                 451460
Part Thermosensible                                451460
Consommation Secteur Inconnu (MWh)                 428466
Nombre de points Secteur Inconnu                   429833
Nombre de mailles secretisées (secteur inconnu)    425408
Indice qualité Non Affecté                         435572
Code Commune                                            0
Libellé Commune                                         0
Code EPCI                                               0
Libellé EPCI                                            0
Code Département                                        0
Libellé Département                                     0
Code Région                                             0
Libellé Région                                          0
id_filiere                                              0
Consommation totale (MWh)                            2769
Code_postal                                             0
dtype: int64

In [9]:
import pandas as pd
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    dbname="consommation_energie",
    user="postgres",
    password="1212.Y8m"
)

df = pd.read_sql_query("SELECT * FROM consommation_energie", conn)

C:\Users\mehal\AppData\Local\Temp\ipykernel_1724\1221454800.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM consommation_energie", conn)

In [10]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\mehal\anaconda3\lib\site-packages (2.9.10)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
with open('ton_fichier.csv', 'r', encoding='utf-8') as f:
    print(sum(1 for line in f))

In [11]:
# Création du curseur pour exécuter des requêtes
cur = conn.cursor()

In [12]:
# Afficher la structure de la table
cur.execute("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'consommation_energie';
""")
columns = cur.fetchall()

# Afficher la structure des colonnes
for column in columns:
    print(column)

('operateur', 'text')
('annee', 'integer')
('filiere', 'text')
('consommation_agriculture_mwh', 'numeric')
('nombre_points_agriculture', 'integer')
('indice_qualite_agriculture', 'numeric')
('consommation_industrie_mwh', 'numeric')
('nombre_points_industrie', 'integer')
('indice_qualite_industrie', 'numeric')
('consommation_tertiaire_mwh', 'numeric')
('nombre_points_tertiaire', 'integer')
('indice_qualite_tertiaire', 'numeric')
('consommation_residentiel_mwh', 'numeric')
('nombre_points_residentiel', 'integer')
('indice_qualite_residentiel', 'numeric')
('thermosensibilite_mwh_par_deg_jour', 'numeric')
('part_thermosensible', 'numeric')
('consommation_secteur_inconnu_mwh', 'numeric')
('nombre_points_secteur_inconnu', 'integer')
('indice_qualite_non_affecte', 'numeric')
('code_commune', 'text')
('libelle_commune', 'text')
('code_epci', 'text')
('libelle_epci', 'text')
('code_departement', 'text')
('libelle_departement', 'text')
('code_region', 'text')
('libelle_region', 'text')
('id_filiere', 'integer')
('consommation_totale_mwh', 'numeric')
('code_postal', 'text')

In [13]:
conn.rollback()

In [14]:
for col_name, col_type in columns:
    if col_type.startswith("character") or col_type == "text":
        query = f"SELECT COUNT(*) FROM consommation_energie WHERE {col_name} IS NOT NULL AND {col_name} <> '';"
    else:
        query = f"SELECT COUNT(*) FROM consommation_energie WHERE {col_name} IS NOT NULL;"
    
    cur.execute(query)
    count = cur.fetchone()[0]
    
    # Afficher même si la colonne est vide
    if count == 0:
        print(f"Colonne vide : {col_name}")
    else:
        print(f"Colonne {col_name} a {count} valeurs non nulles")

Colonne operateur a 501565 valeurs non nulles
Colonne annee a 501565 valeurs non nulles
Colonne filiere a 501565 valeurs non nulles
Colonne consommation_agriculture_mwh a 501565 valeurs non nulles
Colonne nombre_points_agriculture a 501565 valeurs non nulles
Colonne indice_qualite_agriculture a 501565 valeurs non nulles
Colonne consommation_industrie_mwh a 501565 valeurs non nulles
Colonne nombre_points_industrie a 501565 valeurs non nulles
Colonne indice_qualite_industrie a 501565 valeurs non nulles
Colonne consommation_tertiaire_mwh a 501565 valeurs non nulles
Colonne nombre_points_tertiaire a 501565 valeurs non nulles
Colonne indice_qualite_tertiaire a 501565 valeurs non nulles
Colonne consommation_residentiel_mwh a 501565 valeurs non nulles
Colonne nombre_points_residentiel a 501565 valeurs non nulles
Colonne indice_qualite_residentiel a 501565 valeurs non nulles
Colonne thermosensibilite_mwh_par_deg_jour a 501565 valeurs non nulles
Colonne part_thermosensible a 501565 valeurs non nulles
Colonne consommation_secteur_inconnu_mwh a 501565 valeurs non nulles
Colonne nombre_points_secteur_inconnu a 501565 valeurs non nulles
Colonne indice_qualite_non_affecte a 501565 valeurs non nulles
Colonne code_commune a 501565 valeurs non nulles
Colonne libelle_commune a 501547 valeurs non nulles
Colonne code_epci a 501565 valeurs non nulles
Colonne libelle_epci a 501547 valeurs non nulles
Colonne code_departement a 501565 valeurs non nulles
Colonne libelle_departement a 501565 valeurs non nulles
Colonne code_region a 501565 valeurs non nulles
Colonne libelle_region a 501565 valeurs non nulles
Colonne id_filiere a 501565 valeurs non nulles
Colonne consommation_totale_mwh a 501565 valeurs non nulles
Colonne code_postal a 501426 valeurs non nulles

In [15]:
# Récupérer les colonnes de la table
cur.execute("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'consommation_energie';
""")
columns = cur.fetchall()

# Générer et exécuter une requête pour compter les valeurs égales à zéro
for col_name, col_type in columns:
    if col_type.startswith("character") or col_type == "text":
        # Pour les colonnes de type texte, on ignore les comparaisons avec 0
        query = f"SELECT COUNT(*) FROM consommation_energie WHERE {col_name} = '';"
    else:
        # Pour les autres types de données, on cherche les valeurs égales à zéro
        query = f"SELECT COUNT(*) FROM consommation_energie WHERE {col_name} = 0;"
    
    cur.execute(query)
    count = cur.fetchone()[0]
    
    if count > 0:
        print(f"Colonne {col_name} a {count} valeurs égales à zéro.")

Colonne consommation_agriculture_mwh a 333159 valeurs égales à zéro.
Colonne nombre_points_agriculture a 333088 valeurs égales à zéro.
Colonne indice_qualite_agriculture a 337145 valeurs égales à zéro.
Colonne consommation_industrie_mwh a 264154 valeurs égales à zéro.
Colonne nombre_points_industrie a 264138 valeurs égales à zéro.
Colonne indice_qualite_industrie a 273267 valeurs égales à zéro.
Colonne consommation_tertiaire_mwh a 161926 valeurs égales à zéro.
Colonne nombre_points_tertiaire a 162113 valeurs égales à zéro.
Colonne indice_qualite_tertiaire a 173684 valeurs égales à zéro.
Colonne consommation_residentiel_mwh a 24245 valeurs égales à zéro.
Colonne nombre_points_residentiel a 24249 valeurs égales à zéro.
Colonne indice_qualite_residentiel a 75007 valeurs égales à zéro.
Colonne thermosensibilite_mwh_par_deg_jour a 451460 valeurs égales à zéro.
Colonne part_thermosensible a 451460 valeurs égales à zéro.
Colonne consommation_secteur_inconnu_mwh a 428466 valeurs égales à zéro.
Colonne nombre_points_secteur_inconnu a 429833 valeurs égales à zéro.
Colonne indice_qualite_non_affecte a 435572 valeurs égales à zéro.
Colonne consommation_totale_mwh a 2769 valeurs égales à zéro.

In [16]:
# Récupérer toute la table consommation_energie
cur.execute("SELECT * FROM consommation_energie;")
rows = cur.fetchall()

# Afficher les résultats sous forme de DataFrame
df_avant_supp_colonne = pd.DataFrame(rows, columns=[desc[0] for desc in cur.description])

# Afficher la table entière
df_avant_supp_colonne

,operateur,annee,filiere,consommation_agriculture_mwh,nombre_points_agriculture,indice_qualite_agriculture,consommation_industrie_mwh,nombre_points_industrie,indice_qualite_industrie,consommation_tertiaire_mwh,...,libelle_commune,code_epci,libelle_epci,code_departement,libelle_departement,code_region,libelle_region,id_filiere,consommation_totale_mwh,code_postal
0,GRDF,2021,Gaz,0.0,0,0.0,4662.25037,10,0.348,3733.40577,...,Appoigny,200067114,CA de l'Auxerrois,89,Yonne,27,Bourgogne-Franche-ComtÃ©,200,19903.81639,89380
1,GRDF,2021,Gaz,0.0,0,0.0,466.96205,4,0.631,676.52362,...,Augy,200067114,CA de l'Auxerrois,89,Yonne,27,Bourgogne-Franche-ComtÃ©,200,5936.61816,89290
2,GRDF,2021,Gaz,0.0,0,0.0,33572.36146,14,0.476,22824.80077,...,Avallon,200039758,"CC Avallon, VÃ©zelay, Morvan",89,Yonne,27,Bourgogne-Franche-ComtÃ©,200,79188.02222,89200
3,GRDF,2021,Gaz,0.0,0,0.0,84.09507,1,0.0,105.14177,...,Bassou,248900383,CC de l'AgglomÃ©ration Migennoise,89,Yonne,27,Bourgogne-Franche-ComtÃ©,200,2601.05236,89400
4,GRDF,2021,Gaz,0.0,0,0.0,0.0,0,0.0,70.76689,...,Bazarnes,200067080,CC Chablis Villages et Terroirs,89,Yonne,27,Bourgogne-Franche-ComtÃ©,200,1195.97512,89460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501560,Enedis,2012,ElectricitÃ©,0.0,0,0.0,135.46,1,0.927,0.0,...,Saint-Ulphace,247200686,CC du Pays de l'Huisne Sarthoise,72,Sarthe,52,Pays de la Loire,100,1284.06,72320
501561,Enedis,2012,ElectricitÃ©,0.0,0,0.0,387.38,1,0.911,142.07,...,Saint-Vincent-du-LorouÃ«r,200070373,CC Loir-LucÃ©-BercÃ©,72,Sarthe,52,Pays de la Loire,100,4203.72,72150
501562,Enedis,2012,ElectricitÃ©,238.2,6,0.989,29.49,1,1.0,0.0,...,SavignÃ©-sous-le-Lude,200073112,CC Sud Sarthe,72,Sarthe,52,Pays de la Loire,100,2093.96,72800
501563,Enedis,2012,ElectricitÃ©,0.0,0,0.0,19659.51,7,0.997,7679.61,...,Solesmes,247200090,CC de SablÃ©-sur-Sarthe,72,Sarthe,52,Pays de la Loire,100,33036.56,72300
501564,Enedis,2012,ElectricitÃ©,36.03,1,1.0,0.0,0,0.0,13.47,...,SouillÃ©,200068963,CC Maine CÅ“ur de Sarthe,72,Sarthe,52,Pays de la Loire,100,2479.62,72380

In [17]:
# Récupérer les noms des colonnes de la table consommation_energie
cur.execute("""
    SELECT column_name 
    FROM information_schema.columns 
    WHERE table_name = 'consommation_energie';
""")
columns = cur.fetchall()

# Afficher les noms des colonnes
for column in columns:
    print(column[0])

operateur
annee
filiere
consommation_agriculture_mwh
nombre_points_agriculture
indice_qualite_agriculture
consommation_industrie_mwh
nombre_points_industrie
indice_qualite_industrie
consommation_tertiaire_mwh
nombre_points_tertiaire
indice_qualite_tertiaire
consommation_residentiel_mwh
nombre_points_residentiel
indice_qualite_residentiel
thermosensibilite_mwh_par_deg_jour
part_thermosensible
consommation_secteur_inconnu_mwh
nombre_points_secteur_inconnu
indice_qualite_non_affecte
code_commune
libelle_commune
code_epci
libelle_epci
code_departement
libelle_departement
code_region
libelle_region
id_filiere
consommation_totale_mwh
code_postal

Etant donné qu'il y as des colonnes qui ne servent a rien pour l'analyse et en plus de cela c'est colonnes sont vide j'ai donc pris la décision de supprimer  celles ci de la base de donnés. Elles ne sont donc pas pertinente. 
Les colonnes que je vais supprimer sont 

     nombre_mailles_secretisees_agriculture',
    'nombre_mailles_secretisees_industrie',
    'nombre_mailles_secretisees_tertiaire',
    'nombre_mailles_secretisees_residentiel',
    'nombre_mailles_secretisees_secteur_inconnu',
    'indice_qualite_agriculture',
    'indice_qualite_industrie',
    'indice_qualite_tertiaire',
    'indice_qualite_residentiel',
    'indice_qualite_non_affecte',
    'thermosensibilite_mwh_par_deg_jour',
    'part_thermosensible',
    'consommation_secteur_inconnu_mwh',
    'nombre_points_secteur_inconnu'

En amont je vais enregistré le df et ensuite sup les colonnes inutile a l'analyse

In [1]:
import pandas as pd

# Lire le fichier avec l'encodage le plus probable
df = pd.read_csv(r"C:\Users\mehal\Desktop\Yamina\vsc\backup_consommation_energie.csv", encoding="utf-8", low_memory=False)

# Corriger les chaînes avec un double décodage
def reencode(val):
    if isinstance(val, str):
        try:
            return val.encode('latin1').decode('utf-8')
        except:
            return val
    return val

# Appliquer la correction
df = df.map(reencode)

# Tester le résultat
print(df["filiere"].unique())
print(df["libelle_commune"].head())

['Electricité' 'Gaz']
0        Uffheim
1     Ungersheim
2          Urbès
3    Urschenheim
4    Vieux-Thann
Name: libelle_commune, dtype: object

In [2]:
df

,operateur,annee,filiere,consommation_agriculture_mwh,nombre_points_agriculture,nombre_mailles_secretisees_agriculture,indice_qualite_agriculture,consommation_industrie_mwh,nombre_points_industrie,nombre_mailles_secretisees_industrie,...,libelle_commune,code_epci,libelle_epci,code_departement,libelle_departement,code_region,libelle_region,id_filiere,consommation_totale_mwh,code_postal
0,Enedis,2011,Electricité,0.00,0,0,0.0,0.00,0,0,...,Uffheim,200066058,CA Saint-Louis Agglomération,68,Haut-Rhin,44,Grand Est,100,3093.56,68510
1,Enedis,2011,Electricité,79.57,2,0,1.0,9138.79,6,0,...,Ungersheim,200066009,CA Mulhouse Alsace Agglomération,68,Haut-Rhin,44,Grand Est,100,17575.27,68190
2,Enedis,2011,Electricité,0.00,0,0,0.0,58.11,2,0,...,Urbès,246800205,CC de la Vallée de Saint-Amarin,68,Haut-Rhin,44,Grand Est,100,1232.12,68121
3,Enedis,2011,Electricité,101.03,2,0,1.0,0.00,0,0,...,Urschenheim,200066025,CC Pays Rhin - Brisach,68,Haut-Rhin,44,Grand Est,100,2548.15,68320
4,Enedis,2011,Electricité,0.00,0,0,0.0,19704.32,20,0,...,Vieux-Thann,200036465,CC de Thann-Cernay,68,Haut-Rhin,44,Grand Est,100,50311.12,68800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501560,Enedis,2011,Electricité,0.00,0,0,0.0,0.00,0,0,...,Storckensohn,246800205,CC de la Vallée de Saint-Amarin,68,Haut-Rhin,44,Grand Est,100,680.36,68470
501561,Enedis,2011,Electricité,0.00,0,0,0.0,206.88,2,0,...,Tagolsheim,200066041,CC Sundgau,68,Haut-Rhin,44,Grand Est,100,2969.57,68720
501562,Enedis,2011,Electricité,0.00,0,0,0.0,0.00,0,0,...,Thannenkirch,246800577,CC du Pays de Ribeauvillé,68,Haut-Rhin,44,Grand Est,100,2158.75,68590
501563,Enedis,2011,Electricité,0.00,0,0,0.0,175.27,1,0,...,Traubach-le-Bas,200066033,CC Sud Alsace Largue,68,Haut-Rhin,44,Grand Est,100,1593.62,68210
501564,Enedis,2011,Electricité,0.00,0,0,0.0,102.69,1,0,...,Traubach-le-Haut,200066033,CC Sud Alsace Largue,68,Haut-Rhin,44,Grand Est,100,1686.22,68210

In [10]:
df

,operateur,annee,filiere,consommation_agriculture_mwh,nombre_points_agriculture,consommation_industrie_mwh,nombre_points_industrie,consommation_tertiaire_mwh,nombre_points_tertiaire,consommation_residentiel_mwh,...,libelle_commune,code_epci,libelle_epci,code_departement,libelle_departement,code_region,libelle_region,id_filiere,consommation_totale_mwh,code_postal
0,Enedis,2011,Electricité,0.00,0,0.00,0,268.85,2,2824.71,...,Uffheim,200066058,CA Saint-Louis Agglomération,68,Haut-Rhin,44,Grand Est,100,3093.56,68510
1,Enedis,2011,Electricité,79.57,2,9138.79,6,2733.83,14,5623.08,...,Ungersheim,200066009,CA Mulhouse Alsace Agglomération,68,Haut-Rhin,44,Grand Est,100,17575.27,68190
2,Enedis,2011,Electricité,0.00,0,58.11,2,45.15,1,1128.86,...,Urbès,246800205,CC de la Vallée de Saint-Amarin,68,Haut-Rhin,44,Grand Est,100,1232.12,68121
3,Enedis,2011,Electricité,101.03,2,0.00,0,0.00,0,2447.12,...,Urschenheim,200066025,CC Pays Rhin - Brisach,68,Haut-Rhin,44,Grand Est,100,2548.15,68320
4,Enedis,2011,Electricité,0.00,0,19704.32,20,2121.96,17,7314.68,...,Vieux-Thann,200036465,CC de Thann-Cernay,68,Haut-Rhin,44,Grand Est,100,50311.12,68800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501560,Enedis,2011,Electricité,0.00,0,0.00,0,0.00,0,680.36,...,Storckensohn,246800205,CC de la Vallée de Saint-Amarin,68,Haut-Rhin,44,Grand Est,100,680.36,68470
501561,Enedis,2011,Electricité,0.00,0,206.88,2,531.46,4,2231.23,...,Tagolsheim,200066041,CC Sundgau,68,Haut-Rhin,44,Grand Est,100,2969.57,68720
501562,Enedis,2011,Electricité,0.00,0,0.00,0,538.36,3,1620.39,...,Thannenkirch,246800577,CC du Pays de Ribeauvillé,68,Haut-Rhin,44,Grand Est,100,2158.75,68590
501563,Enedis,2011,Electricité,0.00,0,175.27,1,0.00,0,1418.35,...,Traubach-le-Bas,200066033,CC Sud Alsace Largue,68,Haut-Rhin,44,Grand Est,100,1593.62,68210
501564,Enedis,2011,Electricité,0.00,0,102.69,1,25.25,1,1558.28,...,Traubach-le-Haut,200066033,CC Sud Alsace Largue,68,Haut-Rhin,44,Grand Est,100,1686.22,68210